
services:
  api:
    build: .
    command: uvicorn Api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  web:
    build: .
    command: uvicorn take_input_web:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    volumes:
      - .:/app